schema_version = "1.0.0"


id = "blender_python_debugger_for_vscode"
name = "Blender Python Debugger for VS Code"
version = "3.0.0"
tagline = "Blender addon for remote debugging python code with VS Code"
maintainer = "johnzero7 <johnzero7@gmail.com>"
type = "add-on"
tags = [
    "Development",
]

website = "https://github.com/johnzero7/blender-python-debugger-for-vscode"

license = [
    "SPDX:GPL-3.0-or-later",
]

copyright = [
    "2026 johnzero7",
]

blender_version_min = "4.2.0"
blender_version_max = ""

platforms = [
    "windows-x64",
    "macos-x64",
    "linux-x64"
]

wheels = []

[permissions]
files = "Required to read python files being debugged"

[build]
paths_exclude_pattern = [
    "__pycache__/",
    "/.git/",
    "/*.zip",
]
